export const qryMainNavigation = groq`
*[_type=="navigation" && _id == "mainNavigation"][0]{
  _id,
  name,
  navigationLinks[]{
    _key,
    name,
    linkType,
    externalLink{
      _type,
      newWindow,
      url
    },
    internalLink{
      _type,
      'slug':reference->slug.current,
      'title':reference->title,
      reference->{
        _id
      }
    },
    anchorLink{
      _type,
      anchor,
      page->{
        _id,
      title,
      'slug':slug.current
      }
    }
  }
}
`;

export const qryFooterNavigation = groq`
*[_type=="navigation" && _id == "footerNavigation"][0]{
  _id,
  name,
  navigationLinks[]{
    _key,
    name,
    linkType,
    externalLink{
      _type,
      newWindow,
      url
    },
    internalLink{
      _type,
      'slug':reference->slug.current,
      'title':reference->title,
      'id':reference->_id,
    },
    anchorLink{
      _type,
      anchor,
      page->{
        _id,
      title,
      'slug':slug.current
      }
    }
  }
}
`;

export const qryMobileNavigation = groq`
*[_type=="navigation" && _id == "mobileNavigation"][0]{
  _id,
  name,
  navigationLinks[]{
    _key,
    name,
    linkType,
    externalLink{
      _type,
      newWindow,
      url
    },
    internalLink{
      _type,
      'slug':reference->slug.current,
      'title':reference->title,
      'id':reference->_id,
    },
    anchorLink{
      _type,
      anchor,
      page->{
        _id,
      title,
      'slug':slug.current
      }
    }
  }
}
`;

export const qryOtherNav = groq`
 *[_type=="navigation" && _id != 'mainNavigation' && _id != 'footerNavigation' && _id != 'mobileNavigation'][0]{
    _id,
    name,
    navigationLinks[]{
      _key,
      name,
      linkType,
      externalLink{
        _type,
        newWindow,
        url
      },
      internalLink{
        _type,
        reference->{
          _id,
          'slug':slug.current,
          title,
        }
      },
      anchorLink{
        _type,
        anchor,
        page->{
          _id,
        title,
        'slug':slug.current
        }
      }
    }
  }
}
`;
